### ISSUE TITLE
pembuatan media promosi

### ISSUE THREAD

**Issue by sazaghi** [sazaghi/PengembanganGiftBox#14]

**Comment by Aminudinsetyaw** [comment]
![Uploading Permasalahan dan solusi selama proses requirement (1).png…]()

**Comment by Aminudinsetyaw** [comment]
![Permasalahan dan solusi selama proses requirement (1)](https://github.com/sazaghi/PengembanganGiftBox/assets/155589288/fdb9cd65-4a40-4159-9f07-da9a250f1eb2)
