### ISSUE TITLE
pembuatan kotak dan fitur utama produk

### ISSUE THREAD

**Issue by sazaghi** [sazaghi/PengembanganGiftBox#8]

**Comment by DwiJullian** [comment]
![Image](https://github.com/sazaghi/PengembanganGiftBox/assets/155231004/903191e5-bf12-4e10-a747-43b2639da03b)

**Comment by DwiJullian** [comment]
https://youtu.be/AdHykmo_Vh8?si=7vBPDGrnR0LscrCz
